package com.wip.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;

/**
 * Data Transfer Object for transferring shipment details between the API layer and the service layer.
 *
 * <p>This DTO represents a shipment record created for a dispatched parcel. It is used
 * in both API responses (to display tracking and delivery information) and in update
 * requests (to modify the current location and estimated delivery date). The
 * {@code trackingNumber} and {@code shipmentDate} are generated by the server and are
 * included only in response payloads. The {@code customerName} and {@code receiverPhone}
 * fields are denormalized from the associated parcel and customer for display convenience.</p>
 *
 * @author Rohith Varma K
 * @version 1.0
 * @since 1.0
 */
public class ShipmentDto {

    /**
     * The unique identifier of the shipment. Populated by the server in response payloads.
     */
    private Long shipmentId;

    /**
     * The ID of the parcel associated with this shipment.
     * Populated in response payloads; must be provided when creating a shipment.
     */
    private Long parcelId;

    /**
     * The system-generated unique tracking number assigned to this shipment.
     * Populated by the server; read-only in client requests.
     */
    private String trackingNumber;

    /**
     * The date on which this shipment was dispatched. Populated by the server
     * on creation; may be updated by admins via update requests.
     */
    private LocalDate shipmentDate;

    /**
     * The current geographic location of the shipment. Required for update requests.
     */
    @NotBlank(message = "Current location is required")
    private String currentLocation;

    /**
     * The estimated date by which the parcel is expected to be delivered.
     * Required for update requests.
     */
    @NotNull(message = "Estimated delivery date is required")
    private LocalDate estimatedDeliveryDate;

    /**
     * The full name of the customer who owns the associated parcel.
     * Denormalized field populated in response payloads for display purposes.
     */
    private String customerName;

    /**
     * The receiver's phone number from the associated parcel.
     * Denormalized field populated in response payloads for display purposes.
     */
    private String receiverPhone;

    /**
     * Returns the unique identifier of this shipment.
     *
     * @return the shipment ID, or {@code null} if not yet persisted
     */
    public Long getShipmentId() {
        return shipmentId;
    }

    /**
     * Sets the unique identifier of this shipment.
     *
     * @param shipmentId the shipment ID to assign
     */
    public void setShipmentId(Long shipmentId) {
        this.shipmentId = shipmentId;
    }

    /**
     * Returns the ID of the parcel associated with this shipment.
     *
     * @return the parcel ID
     */
    public Long getParcelId() {
        return parcelId;
    }

    /**
     * Sets the ID of the parcel associated with this shipment.
     *
     * @param parcelId the parcel ID to assign
     */
    public void setParcelId(Long parcelId) {
        this.parcelId = parcelId;
    }

    /**
     * Returns the unique tracking number assigned to this shipment.
     *
     * @return the tracking number string
     */
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Sets the unique tracking number for this shipment.
     *
     * @param trackingNumber the tracking number to assign
     */
    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    /**
     * Returns the dispatch date of this shipment.
     *
     * @return the shipment date as a {@link LocalDate}
     */
    public LocalDate getShipmentDate() {
        return shipmentDate;
    }

    /**
     * Sets the dispatch date of this shipment.
     *
     * @param shipmentDate the dispatch date to assign
     */
    public void setShipmentDate(LocalDate shipmentDate) {
        this.shipmentDate = shipmentDate;
    }

    /**
     * Returns the current geographic location of this shipment.
     *
     * @return the current location string
     */
    public String getCurrentLocation() {
        return currentLocation;
    }

    /**
     * Sets the current geographic location of this shipment.
     *
     * @param currentLocation the current location to assign; must not be blank
     */
    public void setCurrentLocation(String currentLocation) {
        this.currentLocation = currentLocation;
    }

    /**
     * Returns the estimated delivery date for this shipment.
     *
     * @return the estimated delivery date as a {@link LocalDate}
     */
    public LocalDate getEstimatedDeliveryDate() {
        return estimatedDeliveryDate;
    }

    /**
     * Sets the estimated delivery date for this shipment.
     *
     * @param estimatedDeliveryDate the estimated delivery date to assign; must not be null
     */
    public void setEstimatedDeliveryDate(LocalDate estimatedDeliveryDate) {
        this.estimatedDeliveryDate = estimatedDeliveryDate;
    }

    /**
     * Returns the name of the customer who owns the associated parcel.
     *
     * @return the customer's full name, or {@code null} if not populated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the name of the customer who owns the associated parcel.
     *
     * @param customerName the customer name to assign
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * Returns the receiver's phone number from the associated parcel.
     *
     * @return the receiver's phone number, or {@code null} if not populated
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * Sets the receiver's phone number from the associated parcel.
     *
     * @param receiverPhone the receiver phone number to assign
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }
}
