apiVersion: apps/v1
kind: Deployment
metadata:
  name: couriertrackingsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couriertrackingsystem
  template:
    metadata:
      labels:
        app: couriertrackingsystem
    spec:
      containers:
        - name: couriertrackingsystem
          image: couriertrackingsystem:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/couriertrackingsystem